### ISSUE TITLE
Ember example blank

### ISSUE THREAD

**Issue by jernejc** [tastejs/todomvc#1708]
Hi,

the ember.js example loads blank:
http://todomvc.com/examples/emberjs/index.html/examples/emberjs/

**Comment by Otolock** [comment]
It looks like the link is bad. If you erase the extra `/examples/emberjs/`, it loads the app correctly.

**Comment by jernejc** [comment]
Ok, seems like it was fixed. 
That's the link I was being redirected to if visiting: 
http://todomvc.com/examples/emberjs/index.html

Thanks

**Comment by Otolock** [comment]
The app is working, but the redirect on the main page is acting weird for Ember.

**Comment by arthurvr** [comment]
Hm, strange. Closing this as a duplicate of https://github.com/tastejs/todomvc/issues/1695 though.

**Comment by ciroreed** [comment]
Here -> http://todomvc.com/ Ember url is broken or something.. it goes to http://todomvc.com/examples/emberjs which is still broken
